### ISSUE TITLE
Docker usage

### ISSUE THREAD

**Issue by machawk1** [datatogether/sentry#49]
Hey there, thank you for submitting an issue!

We are trying to keep issues for feature requests and bug reports. Please
complete the following checklist before creating a new one:

- [X] Is this a **bug report** (if so, is it something you can **debug and fix**? 
Send a pull request!)
- [ ] feature request
- [ ] support request => Please do not submit support requests here, ask your question 
on [Slack](https://archivers-slack.herokuapp.com/).

---
The README specifies the command, "docker compose up" to install sentry via docker. My docker knowledge is a little rusty, but the aforementioned causes the error, "docker: 'compose' is not a docker command." to be returned. From what I recall, the binary is docker-compose, i.e., the command should be, `docker-compose up` with a very important hyphen.

I could be wrong or my local Docker could be updated, so please sanity check this before making the change to the README.

**Comment by dcwalk** [comment]
I think you are correct, `docker-compose up` is the command I use (and is in our other readmes, e.g., https://github.com/datatogether/webapp)

Thanks for the eagle eyes 🦅

**Comment by dcwalk** [comment]
@machawk1 , I made the small fix in #48 as that is also sprucing up README. I think once that is reviewed and merged we are good :)

**Comment by machawk1** [comment]
@dcwalk Great! I also like the sound of the move from S3 to IPFS in #48. Looking forward to testing sentry further.

Closing this issue.
